export enum Enum__ActivityAction {
  CREATE_WORKSPACE = "CREATE_WORKSPACE",
  UPDATE_WORKSPACE = "UPDATE_WORKSPACE",
  DELETE_WORKSPACE = "DELETE_WORKSPACE",

  CREATE_LAYER = "CREATE_LAYER",
  UPDATE_LAYER = "UPDATE_LAYER",
  DELETE_LAYER = "DELETE_LAYER",
}
