export const TIME_ZONES = [
  {
    key: "Africa/Abidjan",
    label: "Africa/Abidjan",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Africa/Accra",
    label: "Africa/Accra",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Africa/Addis_Ababa",
    label: "Africa/Addis_Ababa",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "EAT",
  },
  {
    key: "Africa/Algiers",
    label: "Africa/Algiers",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Africa/Asmara",
    label: "Africa/Asmara",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "EAT",
  },
  {
    key: "Africa/Asmera",
    label: "Africa/Asmera",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "EAT",
  },
  {
    key: "Africa/Bamako",
    label: "Africa/Bamako",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Africa/Bangui",
    label: "Africa/Bangui",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "WAT",
  },
  {
    key: "Africa/Banjul",
    label: "Africa/Banjul",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Africa/Bissau",
    label: "Africa/Bissau",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Africa/Blantyre",
    label: "Africa/Blantyre",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "CAT",
  },
  {
    key: "Africa/Brazzaville",
    label: "Africa/Brazzaville",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "WAT",
  },
  {
    key: "Africa/Bujumbura",
    label: "Africa/Bujumbura",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "CAT",
  },
  {
    key: "Africa/Cairo",
    label: "Africa/Cairo",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Africa/Casablanca",
    label: "Africa/Casablanca",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "+00",
  },
  {
    key: "Africa/Ceuta",
    label: "Africa/Ceuta",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Africa/Conakry",
    label: "Africa/Conakry",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Africa/Dakar",
    label: "Africa/Dakar",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Africa/Dar_es_Salaam",
    label: "Africa/Dar_es_Salaam",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "EAT",
  },
  {
    key: "Africa/Djibouti",
    label: "Africa/Djibouti",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "EAT",
  },
  {
    key: "Africa/Douala",
    label: "Africa/Douala",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "WAT",
  },
  {
    key: "Africa/El_Aaiun",
    label: "Africa/El_Aaiun",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "+00",
  },
  {
    key: "Africa/Freetown",
    label: "Africa/Freetown",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Africa/Gaborone",
    label: "Africa/Gaborone",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "CAT",
  },
  {
    key: "Africa/Harare",
    label: "Africa/Harare",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "CAT",
  },
  {
    key: "Africa/Johannesburg",
    label: "Africa/Johannesburg",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "SAST",
  },
  {
    key: "Africa/Juba",
    label: "Africa/Juba",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "CAT",
  },
  {
    key: "Africa/Kampala",
    label: "Africa/Kampala",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "EAT",
  },
  {
    key: "Africa/Khartoum",
    label: "Africa/Khartoum",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "CAT",
  },
  {
    key: "Africa/Kigali",
    label: "Africa/Kigali",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "CAT",
  },
  {
    key: "Africa/Kinshasa",
    label: "Africa/Kinshasa",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "WAT",
  },
  {
    key: "Africa/Lagos",
    label: "Africa/Lagos",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "WAT",
  },
  {
    key: "Africa/Libreville",
    label: "Africa/Libreville",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "WAT",
  },
  {
    key: "Africa/Lome",
    label: "Africa/Lome",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Africa/Luanda",
    label: "Africa/Luanda",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "WAT",
  },
  {
    key: "Africa/Lubumbashi",
    label: "Africa/Lubumbashi",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "CAT",
  },
  {
    key: "Africa/Lusaka",
    label: "Africa/Lusaka",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "CAT",
  },
  {
    key: "Africa/Malabo",
    label: "Africa/Malabo",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "WAT",
  },
  {
    key: "Africa/Maputo",
    label: "Africa/Maputo",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "CAT",
  },
  {
    key: "Africa/Maseru",
    label: "Africa/Maseru",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "SAST",
  },
  {
    key: "Africa/Mbabane",
    label: "Africa/Mbabane",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "SAST",
  },
  {
    key: "Africa/Mogadishu",
    label: "Africa/Mogadishu",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "EAT",
  },
  {
    key: "Africa/Monrovia",
    label: "Africa/Monrovia",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Africa/Nairobi",
    label: "Africa/Nairobi",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "EAT",
  },
  {
    key: "Africa/Ndjamena",
    label: "Africa/Ndjamena",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "WAT",
  },
  {
    key: "Africa/Niamey",
    label: "Africa/Niamey",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "WAT",
  },
  {
    key: "Africa/Nouakchott",
    label: "Africa/Nouakchott",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Africa/Ouagadougou",
    label: "Africa/Ouagadougou",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Africa/Porto-Novo",
    label: "Africa/Porto-Novo",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "WAT",
  },
  {
    key: "Africa/Sao_Tome",
    label: "Africa/Sao_Tome",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Africa/Timbuktu",
    label: "Africa/Timbuktu",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Africa/Tripoli",
    label: "Africa/Tripoli",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Africa/Tunis",
    label: "Africa/Tunis",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Africa/Windhoek",
    label: "Africa/Windhoek",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "CAT",
  },
  {
    key: "America/Adak",
    label: "America/Adak",
    offset: -540,
    offsetMs: -32400000,
    formattedOffset: "UTC-09:00",
    localAbbr: "HDT",
  },
  {
    key: "America/Anchorage",
    label: "America/Anchorage",
    offset: -480,
    offsetMs: -28800000,
    formattedOffset: "UTC-08:00",
    localAbbr: "AKDT",
  },
  {
    key: "America/Anguilla",
    label: "America/Anguilla",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/Antigua",
    label: "America/Antigua",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/Araguaina",
    label: "America/Araguaina",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Argentina/Buenos_Aires",
    label: "America/Argentina/Buenos_Aires",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Argentina/Catamarca",
    label: "America/Argentina/Catamarca",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Argentina/ComodRivadavia",
    label: "America/Argentina/ComodRivadavia",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Argentina/Cordoba",
    label: "America/Argentina/Cordoba",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Argentina/Jujuy",
    label: "America/Argentina/Jujuy",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Argentina/La_Rioja",
    label: "America/Argentina/La_Rioja",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Argentina/Mendoza",
    label: "America/Argentina/Mendoza",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Argentina/Rio_Gallegos",
    label: "America/Argentina/Rio_Gallegos",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Argentina/Salta",
    label: "America/Argentina/Salta",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Argentina/San_Juan",
    label: "America/Argentina/San_Juan",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Argentina/San_Luis",
    label: "America/Argentina/San_Luis",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Argentina/Tucuman",
    label: "America/Argentina/Tucuman",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Argentina/Ushuaia",
    label: "America/Argentina/Ushuaia",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Aruba",
    label: "America/Aruba",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/Asuncion",
    label: "America/Asuncion",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Atikokan",
    label: "America/Atikokan",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "EST",
  },
  {
    key: "America/Atka",
    label: "America/Atka",
    offset: -540,
    offsetMs: -32400000,
    formattedOffset: "UTC-09:00",
    localAbbr: "HDT",
  },
  {
    key: "America/Bahia",
    label: "America/Bahia",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Bahia_Banderas",
    label: "America/Bahia_Banderas",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "CST",
  },
  {
    key: "America/Barbados",
    label: "America/Barbados",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/Belem",
    label: "America/Belem",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Belize",
    label: "America/Belize",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "CST",
  },
  {
    key: "America/Blanc-Sablon",
    label: "America/Blanc-Sablon",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/Boa_Vista",
    label: "America/Boa_Vista",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "-04",
  },
  {
    key: "America/Bogota",
    label: "America/Bogota",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "-05",
  },
  {
    key: "America/Boise",
    label: "America/Boise",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "MDT",
  },
  {
    key: "America/Buenos_Aires",
    label: "America/Buenos_Aires",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Cambridge_Bay",
    label: "America/Cambridge_Bay",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "MDT",
  },
  {
    key: "America/Campo_Grande",
    label: "America/Campo_Grande",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "-04",
  },
  {
    key: "America/Cancun",
    label: "America/Cancun",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "EST",
  },
  {
    key: "America/Caracas",
    label: "America/Caracas",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "-04",
  },
  {
    key: "America/Catamarca",
    label: "America/Catamarca",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Cayenne",
    label: "America/Cayenne",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Cayman",
    label: "America/Cayman",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "EST",
  },
  {
    key: "America/Chicago",
    label: "America/Chicago",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "CDT",
  },
  {
    key: "America/Chihuahua",
    label: "America/Chihuahua",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "CST",
  },
  {
    key: "America/Ciudad_Juarez",
    label: "America/Ciudad_Juarez",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "MDT",
  },
  {
    key: "America/Coral_Harbour",
    label: "America/Coral_Harbour",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "EST",
  },
  {
    key: "America/Cordoba",
    label: "America/Cordoba",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Costa_Rica",
    label: "America/Costa_Rica",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "CST",
  },
  {
    key: "America/Creston",
    label: "America/Creston",
    offset: -420,
    offsetMs: -25200000,
    formattedOffset: "UTC-07:00",
    localAbbr: "MST",
  },
  {
    key: "America/Cuiaba",
    label: "America/Cuiaba",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "-04",
  },
  {
    key: "America/Curacao",
    label: "America/Curacao",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/Danmarkshavn",
    label: "America/Danmarkshavn",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "America/Dawson",
    label: "America/Dawson",
    offset: -420,
    offsetMs: -25200000,
    formattedOffset: "UTC-07:00",
    localAbbr: "MST",
  },
  {
    key: "America/Dawson_Creek",
    label: "America/Dawson_Creek",
    offset: -420,
    offsetMs: -25200000,
    formattedOffset: "UTC-07:00",
    localAbbr: "MST",
  },
  {
    key: "America/Denver",
    label: "America/Denver",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "MDT",
  },
  {
    key: "America/Detroit",
    label: "America/Detroit",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "America/Dominica",
    label: "America/Dominica",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/Edmonton",
    label: "America/Edmonton",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "MDT",
  },
  {
    key: "America/Eirunepe",
    label: "America/Eirunepe",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "-05",
  },
  {
    key: "America/El_Salvador",
    label: "America/El_Salvador",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "CST",
  },
  {
    key: "America/Ensenada",
    label: "America/Ensenada",
    offset: -420,
    offsetMs: -25200000,
    formattedOffset: "UTC-07:00",
    localAbbr: "PDT",
  },
  {
    key: "America/Fort_Nelson",
    label: "America/Fort_Nelson",
    offset: -420,
    offsetMs: -25200000,
    formattedOffset: "UTC-07:00",
    localAbbr: "MST",
  },
  {
    key: "America/Fort_Wayne",
    label: "America/Fort_Wayne",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "America/Fortaleza",
    label: "America/Fortaleza",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Glace_Bay",
    label: "America/Glace_Bay",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "ADT",
  },
  {
    key: "America/Godthab",
    label: "America/Godthab",
    offset: -120,
    offsetMs: -7200000,
    formattedOffset: "UTC-02:00",
    localAbbr: "-02",
  },
  {
    key: "America/Goose_Bay",
    label: "America/Goose_Bay",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "ADT",
  },
  {
    key: "America/Grand_Turk",
    label: "America/Grand_Turk",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "America/Grenada",
    label: "America/Grenada",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/Guadeloupe",
    label: "America/Guadeloupe",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/Guatemala",
    label: "America/Guatemala",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "CST",
  },
  {
    key: "America/Guayaquil",
    label: "America/Guayaquil",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "-05",
  },
  {
    key: "America/Guyana",
    label: "America/Guyana",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "-04",
  },
  {
    key: "America/Halifax",
    label: "America/Halifax",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "ADT",
  },
  {
    key: "America/Havana",
    label: "America/Havana",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "CDT",
  },
  {
    key: "America/Hermosillo",
    label: "America/Hermosillo",
    offset: -420,
    offsetMs: -25200000,
    formattedOffset: "UTC-07:00",
    localAbbr: "MST",
  },
  {
    key: "America/Indiana/Indianapolis",
    label: "America/Indiana/Indianapolis",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "America/Indiana/Knox",
    label: "America/Indiana/Knox",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "CDT",
  },
  {
    key: "America/Indiana/Marengo",
    label: "America/Indiana/Marengo",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "America/Indiana/Petersburg",
    label: "America/Indiana/Petersburg",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "America/Indiana/Tell_City",
    label: "America/Indiana/Tell_City",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "CDT",
  },
  {
    key: "America/Indiana/Vevay",
    label: "America/Indiana/Vevay",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "America/Indiana/Vincennes",
    label: "America/Indiana/Vincennes",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "America/Indiana/Winamac",
    label: "America/Indiana/Winamac",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "America/Indianapolis",
    label: "America/Indianapolis",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "America/Inuvik",
    label: "America/Inuvik",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "MDT",
  },
  {
    key: "America/Iqaluit",
    label: "America/Iqaluit",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "America/Jamaica",
    label: "America/Jamaica",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "EST",
  },
  {
    key: "America/Jujuy",
    label: "America/Jujuy",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Juneau",
    label: "America/Juneau",
    offset: -480,
    offsetMs: -28800000,
    formattedOffset: "UTC-08:00",
    localAbbr: "AKDT",
  },
  {
    key: "America/Kentucky/Louisville",
    label: "America/Kentucky/Louisville",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "America/Kentucky/Monticello",
    label: "America/Kentucky/Monticello",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "America/Knox_IN",
    label: "America/Knox_IN",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "CDT",
  },
  {
    key: "America/Kralendijk",
    label: "America/Kralendijk",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/La_Paz",
    label: "America/La_Paz",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "-04",
  },
  {
    key: "America/Lima",
    label: "America/Lima",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "-05",
  },
  {
    key: "America/Los_Angeles",
    label: "America/Los_Angeles",
    offset: -420,
    offsetMs: -25200000,
    formattedOffset: "UTC-07:00",
    localAbbr: "PDT",
  },
  {
    key: "America/Louisville",
    label: "America/Louisville",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "America/Lower_Princes",
    label: "America/Lower_Princes",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/Maceio",
    label: "America/Maceio",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Managua",
    label: "America/Managua",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "CST",
  },
  {
    key: "America/Manaus",
    label: "America/Manaus",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "-04",
  },
  {
    key: "America/Marigot",
    label: "America/Marigot",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/Martinique",
    label: "America/Martinique",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/Matamoros",
    label: "America/Matamoros",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "CDT",
  },
  {
    key: "America/Mazatlan",
    label: "America/Mazatlan",
    offset: -420,
    offsetMs: -25200000,
    formattedOffset: "UTC-07:00",
    localAbbr: "MST",
  },
  {
    key: "America/Mendoza",
    label: "America/Mendoza",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Menominee",
    label: "America/Menominee",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "CDT",
  },
  {
    key: "America/Merida",
    label: "America/Merida",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "CST",
  },
  {
    key: "America/Metlakatla",
    label: "America/Metlakatla",
    offset: -480,
    offsetMs: -28800000,
    formattedOffset: "UTC-08:00",
    localAbbr: "AKDT",
  },
  {
    key: "America/Mexico_City",
    label: "America/Mexico_City",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "CST",
  },
  {
    key: "America/Miquelon",
    label: "America/Miquelon",
    offset: -120,
    offsetMs: -7200000,
    formattedOffset: "UTC-02:00",
    localAbbr: "-02",
  },
  {
    key: "America/Moncton",
    label: "America/Moncton",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "ADT",
  },
  {
    key: "America/Monterrey",
    label: "America/Monterrey",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "CST",
  },
  {
    key: "America/Montevideo",
    label: "America/Montevideo",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Montreal",
    label: "America/Montreal",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "America/Montserrat",
    label: "America/Montserrat",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/Nassau",
    label: "America/Nassau",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "America/New_York",
    label: "America/New_York",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "America/Nipigon",
    label: "America/Nipigon",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "America/Nome",
    label: "America/Nome",
    offset: -480,
    offsetMs: -28800000,
    formattedOffset: "UTC-08:00",
    localAbbr: "AKDT",
  },
  {
    key: "America/Noronha",
    label: "America/Noronha",
    offset: -120,
    offsetMs: -7200000,
    formattedOffset: "UTC-02:00",
    localAbbr: "-02",
  },
  {
    key: "America/North_Dakota/Beulah",
    label: "America/North_Dakota/Beulah",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "CDT",
  },
  {
    key: "America/North_Dakota/Center",
    label: "America/North_Dakota/Center",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "CDT",
  },
  {
    key: "America/North_Dakota/New_Salem",
    label: "America/North_Dakota/New_Salem",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "CDT",
  },
  {
    key: "America/Nuuk",
    label: "America/Nuuk",
    offset: -120,
    offsetMs: -7200000,
    formattedOffset: "UTC-02:00",
    localAbbr: "-02",
  },
  {
    key: "America/Ojinaga",
    label: "America/Ojinaga",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "CDT",
  },
  {
    key: "America/Panama",
    label: "America/Panama",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "EST",
  },
  {
    key: "America/Pangnirtung",
    label: "America/Pangnirtung",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "America/Paramaribo",
    label: "America/Paramaribo",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Phoenix",
    label: "America/Phoenix",
    offset: -420,
    offsetMs: -25200000,
    formattedOffset: "UTC-07:00",
    localAbbr: "MST",
  },
  {
    key: "America/Port-au-Prince",
    label: "America/Port-au-Prince",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "America/Port_of_Spain",
    label: "America/Port_of_Spain",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/Porto_Acre",
    label: "America/Porto_Acre",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "-05",
  },
  {
    key: "America/Porto_Velho",
    label: "America/Porto_Velho",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "-04",
  },
  {
    key: "America/Puerto_Rico",
    label: "America/Puerto_Rico",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/Punta_Arenas",
    label: "America/Punta_Arenas",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Rainy_River",
    label: "America/Rainy_River",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "CDT",
  },
  {
    key: "America/Rankin_Inlet",
    label: "America/Rankin_Inlet",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "CDT",
  },
  {
    key: "America/Recife",
    label: "America/Recife",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Regina",
    label: "America/Regina",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "CST",
  },
  {
    key: "America/Resolute",
    label: "America/Resolute",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "CDT",
  },
  {
    key: "America/Rio_Branco",
    label: "America/Rio_Branco",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "-05",
  },
  {
    key: "America/Rosario",
    label: "America/Rosario",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Santa_Isabel",
    label: "America/Santa_Isabel",
    offset: -420,
    offsetMs: -25200000,
    formattedOffset: "UTC-07:00",
    localAbbr: "PDT",
  },
  {
    key: "America/Santarem",
    label: "America/Santarem",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Santiago",
    label: "America/Santiago",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Santo_Domingo",
    label: "America/Santo_Domingo",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/Sao_Paulo",
    label: "America/Sao_Paulo",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "America/Scoresbysund",
    label: "America/Scoresbysund",
    offset: -120,
    offsetMs: -7200000,
    formattedOffset: "UTC-02:00",
    localAbbr: "-02",
  },
  {
    key: "America/Shiprock",
    label: "America/Shiprock",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "MDT",
  },
  {
    key: "America/Sitka",
    label: "America/Sitka",
    offset: -480,
    offsetMs: -28800000,
    formattedOffset: "UTC-08:00",
    localAbbr: "AKDT",
  },
  {
    key: "America/St_Barthelemy",
    label: "America/St_Barthelemy",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/St_Johns",
    label: "America/St_Johns",
    offset: -150,
    offsetMs: -9000000,
    formattedOffset: "UTC-02:30",
    localAbbr: "NDT",
  },
  {
    key: "America/St_Kitts",
    label: "America/St_Kitts",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/St_Lucia",
    label: "America/St_Lucia",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/St_Thomas",
    label: "America/St_Thomas",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/St_Vincent",
    label: "America/St_Vincent",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/Swift_Current",
    label: "America/Swift_Current",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "CST",
  },
  {
    key: "America/Tegucigalpa",
    label: "America/Tegucigalpa",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "CST",
  },
  {
    key: "America/Thule",
    label: "America/Thule",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "ADT",
  },
  {
    key: "America/Thunder_Bay",
    label: "America/Thunder_Bay",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "America/Tijuana",
    label: "America/Tijuana",
    offset: -420,
    offsetMs: -25200000,
    formattedOffset: "UTC-07:00",
    localAbbr: "PDT",
  },
  {
    key: "America/Toronto",
    label: "America/Toronto",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "America/Tortola",
    label: "America/Tortola",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/Vancouver",
    label: "America/Vancouver",
    offset: -420,
    offsetMs: -25200000,
    formattedOffset: "UTC-07:00",
    localAbbr: "PDT",
  },
  {
    key: "America/Virgin",
    label: "America/Virgin",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "AST",
  },
  {
    key: "America/Whitehorse",
    label: "America/Whitehorse",
    offset: -420,
    offsetMs: -25200000,
    formattedOffset: "UTC-07:00",
    localAbbr: "MST",
  },
  {
    key: "America/Winnipeg",
    label: "America/Winnipeg",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "CDT",
  },
  {
    key: "America/Yakutat",
    label: "America/Yakutat",
    offset: -480,
    offsetMs: -28800000,
    formattedOffset: "UTC-08:00",
    localAbbr: "AKDT",
  },
  {
    key: "America/Yellowknife",
    label: "America/Yellowknife",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "MDT",
  },
  {
    key: "Antarctica/Casey",
    label: "Antarctica/Casey",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "+08",
  },
  {
    key: "Antarctica/Davis",
    label: "Antarctica/Davis",
    offset: 420,
    offsetMs: 25200000,
    formattedOffset: "UTC+07:00",
    localAbbr: "+07",
  },
  {
    key: "Antarctica/DumontDUrville",
    label: "Antarctica/DumontDUrville",
    offset: 600,
    offsetMs: 36000000,
    formattedOffset: "UTC+10:00",
    localAbbr: "+10",
  },
  {
    key: "Antarctica/Macquarie",
    label: "Antarctica/Macquarie",
    offset: 660,
    offsetMs: 39600000,
    formattedOffset: "UTC+11:00",
    localAbbr: "AEDT",
  },
  {
    key: "Antarctica/Mawson",
    label: "Antarctica/Mawson",
    offset: 300,
    offsetMs: 18000000,
    formattedOffset: "UTC+05:00",
    localAbbr: "+05",
  },
  {
    key: "Antarctica/McMurdo",
    label: "Antarctica/McMurdo",
    offset: 780,
    offsetMs: 46800000,
    formattedOffset: "UTC+13:00",
    localAbbr: "NZDT",
  },
  {
    key: "Antarctica/Palmer",
    label: "Antarctica/Palmer",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "Antarctica/Rothera",
    label: "Antarctica/Rothera",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "Antarctica/South_Pole",
    label: "Antarctica/South_Pole",
    offset: 780,
    offsetMs: 46800000,
    formattedOffset: "UTC+13:00",
    localAbbr: "NZDT",
  },
  {
    key: "Antarctica/Syowa",
    label: "Antarctica/Syowa",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "+03",
  },
  {
    key: "Antarctica/Troll",
    label: "Antarctica/Troll",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "+00",
  },
  {
    key: "Antarctica/Vostok",
    label: "Antarctica/Vostok",
    offset: 300,
    offsetMs: 18000000,
    formattedOffset: "UTC+05:00",
    localAbbr: "+05",
  },
  {
    key: "Arctic/Longyearbyen",
    label: "Arctic/Longyearbyen",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Asia/Aden",
    label: "Asia/Aden",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "+03",
  },
  {
    key: "Asia/Almaty",
    label: "Asia/Almaty",
    offset: 300,
    offsetMs: 18000000,
    formattedOffset: "UTC+05:00",
    localAbbr: "+05",
  },
  {
    key: "Asia/Amman",
    label: "Asia/Amman",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "+03",
  },
  {
    key: "Asia/Anadyr",
    label: "Asia/Anadyr",
    offset: 720,
    offsetMs: 43200000,
    formattedOffset: "UTC+12:00",
    localAbbr: "+12",
  },
  {
    key: "Asia/Aqtau",
    label: "Asia/Aqtau",
    offset: 300,
    offsetMs: 18000000,
    formattedOffset: "UTC+05:00",
    localAbbr: "+05",
  },
  {
    key: "Asia/Aqtobe",
    label: "Asia/Aqtobe",
    offset: 300,
    offsetMs: 18000000,
    formattedOffset: "UTC+05:00",
    localAbbr: "+05",
  },
  {
    key: "Asia/Ashgabat",
    label: "Asia/Ashgabat",
    offset: 300,
    offsetMs: 18000000,
    formattedOffset: "UTC+05:00",
    localAbbr: "+05",
  },
  {
    key: "Asia/Ashkhabad",
    label: "Asia/Ashkhabad",
    offset: 300,
    offsetMs: 18000000,
    formattedOffset: "UTC+05:00",
    localAbbr: "+05",
  },
  {
    key: "Asia/Atyrau",
    label: "Asia/Atyrau",
    offset: 300,
    offsetMs: 18000000,
    formattedOffset: "UTC+05:00",
    localAbbr: "+05",
  },
  {
    key: "Asia/Baghdad",
    label: "Asia/Baghdad",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "+03",
  },
  {
    key: "Asia/Bahrain",
    label: "Asia/Bahrain",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "+03",
  },
  {
    key: "Asia/Baku",
    label: "Asia/Baku",
    offset: 240,
    offsetMs: 14400000,
    formattedOffset: "UTC+04:00",
    localAbbr: "+04",
  },
  {
    key: "Asia/Bangkok",
    label: "Asia/Bangkok",
    offset: 420,
    offsetMs: 25200000,
    formattedOffset: "UTC+07:00",
    localAbbr: "+07",
  },
  {
    key: "Asia/Barnaul",
    label: "Asia/Barnaul",
    offset: 420,
    offsetMs: 25200000,
    formattedOffset: "UTC+07:00",
    localAbbr: "+07",
  },
  {
    key: "Asia/Beirut",
    label: "Asia/Beirut",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Asia/Bishkek",
    label: "Asia/Bishkek",
    offset: 360,
    offsetMs: 21600000,
    formattedOffset: "UTC+06:00",
    localAbbr: "+06",
  },
  {
    key: "Asia/Brunei",
    label: "Asia/Brunei",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "+08",
  },
  {
    key: "Asia/Calcutta",
    label: "Asia/Calcutta",
    offset: 330,
    offsetMs: 19800000,
    formattedOffset: "UTC+05:30",
    localAbbr: "IST",
  },
  {
    key: "Asia/Chita",
    label: "Asia/Chita",
    offset: 540,
    offsetMs: 32400000,
    formattedOffset: "UTC+09:00",
    localAbbr: "+09",
  },
  {
    key: "Asia/Choibalsan",
    label: "Asia/Choibalsan",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "+08",
  },
  {
    key: "Asia/Chongqing",
    label: "Asia/Chongqing",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "CST",
  },
  {
    key: "Asia/Chungking",
    label: "Asia/Chungking",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "CST",
  },
  {
    key: "Asia/Colombo",
    label: "Asia/Colombo",
    offset: 330,
    offsetMs: 19800000,
    formattedOffset: "UTC+05:30",
    localAbbr: "+0530",
  },
  {
    key: "Asia/Dacca",
    label: "Asia/Dacca",
    offset: 360,
    offsetMs: 21600000,
    formattedOffset: "UTC+06:00",
    localAbbr: "+06",
  },
  {
    key: "Asia/Damascus",
    label: "Asia/Damascus",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "+03",
  },
  {
    key: "Asia/Dhaka",
    label: "Asia/Dhaka",
    offset: 360,
    offsetMs: 21600000,
    formattedOffset: "UTC+06:00",
    localAbbr: "+06",
  },
  {
    key: "Asia/Dili",
    label: "Asia/Dili",
    offset: 540,
    offsetMs: 32400000,
    formattedOffset: "UTC+09:00",
    localAbbr: "+09",
  },
  {
    key: "Asia/Dubai",
    label: "Asia/Dubai",
    offset: 240,
    offsetMs: 14400000,
    formattedOffset: "UTC+04:00",
    localAbbr: "+04",
  },
  {
    key: "Asia/Dushanbe",
    label: "Asia/Dushanbe",
    offset: 300,
    offsetMs: 18000000,
    formattedOffset: "UTC+05:00",
    localAbbr: "+05",
  },
  {
    key: "Asia/Famagusta",
    label: "Asia/Famagusta",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Asia/Gaza",
    label: "Asia/Gaza",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Asia/Harbin",
    label: "Asia/Harbin",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "CST",
  },
  {
    key: "Asia/Hebron",
    label: "Asia/Hebron",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Asia/Ho_Chi_Minh",
    label: "Asia/Ho_Chi_Minh",
    offset: 420,
    offsetMs: 25200000,
    formattedOffset: "UTC+07:00",
    localAbbr: "+07",
  },
  {
    key: "Asia/Hong_Kong",
    label: "Asia/Hong_Kong",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "HKT",
  },
  {
    key: "Asia/Hovd",
    label: "Asia/Hovd",
    offset: 420,
    offsetMs: 25200000,
    formattedOffset: "UTC+07:00",
    localAbbr: "+07",
  },
  {
    key: "Asia/Irkutsk",
    label: "Asia/Irkutsk",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "+08",
  },
  {
    key: "Asia/Istanbul",
    label: "Asia/Istanbul",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "+03",
  },
  {
    key: "Asia/Jakarta",
    label: "Asia/Jakarta",
    offset: 420,
    offsetMs: 25200000,
    formattedOffset: "UTC+07:00",
    localAbbr: "WIB",
  },
  {
    key: "Asia/Jayapura",
    label: "Asia/Jayapura",
    offset: 540,
    offsetMs: 32400000,
    formattedOffset: "UTC+09:00",
    localAbbr: "WIT",
  },
  {
    key: "Asia/Jerusalem",
    label: "Asia/Jerusalem",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "IST",
  },
  {
    key: "Asia/Kabul",
    label: "Asia/Kabul",
    offset: 270,
    offsetMs: 16200000,
    formattedOffset: "UTC+04:30",
    localAbbr: "+0430",
  },
  {
    key: "Asia/Kamchatka",
    label: "Asia/Kamchatka",
    offset: 720,
    offsetMs: 43200000,
    formattedOffset: "UTC+12:00",
    localAbbr: "+12",
  },
  {
    key: "Asia/Karachi",
    label: "Asia/Karachi",
    offset: 300,
    offsetMs: 18000000,
    formattedOffset: "UTC+05:00",
    localAbbr: "PKT",
  },
  {
    key: "Asia/Kashgar",
    label: "Asia/Kashgar",
    offset: 360,
    offsetMs: 21600000,
    formattedOffset: "UTC+06:00",
    localAbbr: "+06",
  },
  {
    key: "Asia/Kathmandu",
    label: "Asia/Kathmandu",
    offset: 345,
    offsetMs: 20700000,
    formattedOffset: "UTC+05:45",
    localAbbr: "+0545",
  },
  {
    key: "Asia/Katmandu",
    label: "Asia/Katmandu",
    offset: 345,
    offsetMs: 20700000,
    formattedOffset: "UTC+05:45",
    localAbbr: "+0545",
  },
  {
    key: "Asia/Khandyga",
    label: "Asia/Khandyga",
    offset: 540,
    offsetMs: 32400000,
    formattedOffset: "UTC+09:00",
    localAbbr: "+09",
  },
  {
    key: "Asia/Kolkata",
    label: "Asia/Kolkata",
    offset: 330,
    offsetMs: 19800000,
    formattedOffset: "UTC+05:30",
    localAbbr: "IST",
  },
  {
    key: "Asia/Krasnoyarsk",
    label: "Asia/Krasnoyarsk",
    offset: 420,
    offsetMs: 25200000,
    formattedOffset: "UTC+07:00",
    localAbbr: "+07",
  },
  {
    key: "Asia/Kuala_Lumpur",
    label: "Asia/Kuala_Lumpur",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "+08",
  },
  {
    key: "Asia/Kuching",
    label: "Asia/Kuching",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "+08",
  },
  {
    key: "Asia/Kuwait",
    label: "Asia/Kuwait",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "+03",
  },
  {
    key: "Asia/Macao",
    label: "Asia/Macao",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "CST",
  },
  {
    key: "Asia/Macau",
    label: "Asia/Macau",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "CST",
  },
  {
    key: "Asia/Magadan",
    label: "Asia/Magadan",
    offset: 660,
    offsetMs: 39600000,
    formattedOffset: "UTC+11:00",
    localAbbr: "+11",
  },
  {
    key: "Asia/Makassar",
    label: "Asia/Makassar",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "WITA",
  },
  {
    key: "Asia/Manila",
    label: "Asia/Manila",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "PST",
  },
  {
    key: "Asia/Muscat",
    label: "Asia/Muscat",
    offset: 240,
    offsetMs: 14400000,
    formattedOffset: "UTC+04:00",
    localAbbr: "+04",
  },
  {
    key: "Asia/Nicosia",
    label: "Asia/Nicosia",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Asia/Novokuznetsk",
    label: "Asia/Novokuznetsk",
    offset: 420,
    offsetMs: 25200000,
    formattedOffset: "UTC+07:00",
    localAbbr: "+07",
  },
  {
    key: "Asia/Novosibirsk",
    label: "Asia/Novosibirsk",
    offset: 420,
    offsetMs: 25200000,
    formattedOffset: "UTC+07:00",
    localAbbr: "+07",
  },
  {
    key: "Asia/Omsk",
    label: "Asia/Omsk",
    offset: 360,
    offsetMs: 21600000,
    formattedOffset: "UTC+06:00",
    localAbbr: "+06",
  },
  {
    key: "Asia/Oral",
    label: "Asia/Oral",
    offset: 300,
    offsetMs: 18000000,
    formattedOffset: "UTC+05:00",
    localAbbr: "+05",
  },
  {
    key: "Asia/Phnom_Penh",
    label: "Asia/Phnom_Penh",
    offset: 420,
    offsetMs: 25200000,
    formattedOffset: "UTC+07:00",
    localAbbr: "+07",
  },
  {
    key: "Asia/Pontianak",
    label: "Asia/Pontianak",
    offset: 420,
    offsetMs: 25200000,
    formattedOffset: "UTC+07:00",
    localAbbr: "WIB",
  },
  {
    key: "Asia/Pyongyang",
    label: "Asia/Pyongyang",
    offset: 540,
    offsetMs: 32400000,
    formattedOffset: "UTC+09:00",
    localAbbr: "KST",
  },
  {
    key: "Asia/Qatar",
    label: "Asia/Qatar",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "+03",
  },
  {
    key: "Asia/Qostanay",
    label: "Asia/Qostanay",
    offset: 300,
    offsetMs: 18000000,
    formattedOffset: "UTC+05:00",
    localAbbr: "+05",
  },
  {
    key: "Asia/Qyzylorda",
    label: "Asia/Qyzylorda",
    offset: 300,
    offsetMs: 18000000,
    formattedOffset: "UTC+05:00",
    localAbbr: "+05",
  },
  {
    key: "Asia/Rangoon",
    label: "Asia/Rangoon",
    offset: 390,
    offsetMs: 23400000,
    formattedOffset: "UTC+06:30",
    localAbbr: "+0630",
  },
  {
    key: "Asia/Riyadh",
    label: "Asia/Riyadh",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "+03",
  },
  {
    key: "Asia/Saigon",
    label: "Asia/Saigon",
    offset: 420,
    offsetMs: 25200000,
    formattedOffset: "UTC+07:00",
    localAbbr: "+07",
  },
  {
    key: "Asia/Sakhalin",
    label: "Asia/Sakhalin",
    offset: 660,
    offsetMs: 39600000,
    formattedOffset: "UTC+11:00",
    localAbbr: "+11",
  },
  {
    key: "Asia/Samarkand",
    label: "Asia/Samarkand",
    offset: 300,
    offsetMs: 18000000,
    formattedOffset: "UTC+05:00",
    localAbbr: "+05",
  },
  {
    key: "Asia/Seoul",
    label: "Asia/Seoul",
    offset: 540,
    offsetMs: 32400000,
    formattedOffset: "UTC+09:00",
    localAbbr: "KST",
  },
  {
    key: "Asia/Shanghai",
    label: "Asia/Shanghai",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "CST",
  },
  {
    key: "Asia/Singapore",
    label: "Asia/Singapore",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "+08",
  },
  {
    key: "Asia/Srednekolymsk",
    label: "Asia/Srednekolymsk",
    offset: 660,
    offsetMs: 39600000,
    formattedOffset: "UTC+11:00",
    localAbbr: "+11",
  },
  {
    key: "Asia/Taipei",
    label: "Asia/Taipei",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "CST",
  },
  {
    key: "Asia/Tashkent",
    label: "Asia/Tashkent",
    offset: 300,
    offsetMs: 18000000,
    formattedOffset: "UTC+05:00",
    localAbbr: "+05",
  },
  {
    key: "Asia/Tbilisi",
    label: "Asia/Tbilisi",
    offset: 240,
    offsetMs: 14400000,
    formattedOffset: "UTC+04:00",
    localAbbr: "+04",
  },
  {
    key: "Asia/Tehran",
    label: "Asia/Tehran",
    offset: 210,
    offsetMs: 12600000,
    formattedOffset: "UTC+03:30",
    localAbbr: "+0330",
  },
  {
    key: "Asia/Tel_Aviv",
    label: "Asia/Tel_Aviv",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "IST",
  },
  {
    key: "Asia/Thimbu",
    label: "Asia/Thimbu",
    offset: 360,
    offsetMs: 21600000,
    formattedOffset: "UTC+06:00",
    localAbbr: "+06",
  },
  {
    key: "Asia/Thimphu",
    label: "Asia/Thimphu",
    offset: 360,
    offsetMs: 21600000,
    formattedOffset: "UTC+06:00",
    localAbbr: "+06",
  },
  {
    key: "Asia/Tokyo",
    label: "Asia/Tokyo",
    offset: 540,
    offsetMs: 32400000,
    formattedOffset: "UTC+09:00",
    localAbbr: "JST",
  },
  {
    key: "Asia/Tomsk",
    label: "Asia/Tomsk",
    offset: 420,
    offsetMs: 25200000,
    formattedOffset: "UTC+07:00",
    localAbbr: "+07",
  },
  {
    key: "Asia/Ujung_Pandang",
    label: "Asia/Ujung_Pandang",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "WITA",
  },
  {
    key: "Asia/Ulaanbaatar",
    label: "Asia/Ulaanbaatar",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "+08",
  },
  {
    key: "Asia/Ulan_Bator",
    label: "Asia/Ulan_Bator",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "+08",
  },
  {
    key: "Asia/Urumqi",
    label: "Asia/Urumqi",
    offset: 360,
    offsetMs: 21600000,
    formattedOffset: "UTC+06:00",
    localAbbr: "+06",
  },
  {
    key: "Asia/Ust-Nera",
    label: "Asia/Ust-Nera",
    offset: 600,
    offsetMs: 36000000,
    formattedOffset: "UTC+10:00",
    localAbbr: "+10",
  },
  {
    key: "Asia/Vientiane",
    label: "Asia/Vientiane",
    offset: 420,
    offsetMs: 25200000,
    formattedOffset: "UTC+07:00",
    localAbbr: "+07",
  },
  {
    key: "Asia/Vladivostok",
    label: "Asia/Vladivostok",
    offset: 600,
    offsetMs: 36000000,
    formattedOffset: "UTC+10:00",
    localAbbr: "+10",
  },
  {
    key: "Asia/Yakutsk",
    label: "Asia/Yakutsk",
    offset: 540,
    offsetMs: 32400000,
    formattedOffset: "UTC+09:00",
    localAbbr: "+09",
  },
  {
    key: "Asia/Yangon",
    label: "Asia/Yangon",
    offset: 390,
    offsetMs: 23400000,
    formattedOffset: "UTC+06:30",
    localAbbr: "+0630",
  },
  {
    key: "Asia/Yekaterinburg",
    label: "Asia/Yekaterinburg",
    offset: 300,
    offsetMs: 18000000,
    formattedOffset: "UTC+05:00",
    localAbbr: "+05",
  },
  {
    key: "Asia/Yerevan",
    label: "Asia/Yerevan",
    offset: 240,
    offsetMs: 14400000,
    formattedOffset: "UTC+04:00",
    localAbbr: "+04",
  },
  {
    key: "Atlantic/Azores",
    label: "Atlantic/Azores",
    offset: -60,
    offsetMs: -3600000,
    formattedOffset: "UTC-01:00",
    localAbbr: "-01",
  },
  {
    key: "Atlantic/Bermuda",
    label: "Atlantic/Bermuda",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "ADT",
  },
  {
    key: "Atlantic/Canary",
    label: "Atlantic/Canary",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "WET",
  },
  {
    key: "Atlantic/Cape_Verde",
    label: "Atlantic/Cape_Verde",
    offset: -60,
    offsetMs: -3600000,
    formattedOffset: "UTC-01:00",
    localAbbr: "-01",
  },
  {
    key: "Atlantic/Faeroe",
    label: "Atlantic/Faeroe",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "WET",
  },
  {
    key: "Atlantic/Faroe",
    label: "Atlantic/Faroe",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "WET",
  },
  {
    key: "Atlantic/Jan_Mayen",
    label: "Atlantic/Jan_Mayen",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Atlantic/Madeira",
    label: "Atlantic/Madeira",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "WET",
  },
  {
    key: "Atlantic/Reykjavik",
    label: "Atlantic/Reykjavik",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Atlantic/South_Georgia",
    label: "Atlantic/South_Georgia",
    offset: -120,
    offsetMs: -7200000,
    formattedOffset: "UTC-02:00",
    localAbbr: "-02",
  },
  {
    key: "Atlantic/St_Helena",
    label: "Atlantic/St_Helena",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Atlantic/Stanley",
    label: "Atlantic/Stanley",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "Australia/ACT",
    label: "Australia/ACT",
    offset: 660,
    offsetMs: 39600000,
    formattedOffset: "UTC+11:00",
    localAbbr: "AEDT",
  },
  {
    key: "Australia/Adelaide",
    label: "Australia/Adelaide",
    offset: 630,
    offsetMs: 37800000,
    formattedOffset: "UTC+10:30",
    localAbbr: "ACDT",
  },
  {
    key: "Australia/Brisbane",
    label: "Australia/Brisbane",
    offset: 600,
    offsetMs: 36000000,
    formattedOffset: "UTC+10:00",
    localAbbr: "AEST",
  },
  {
    key: "Australia/Broken_Hill",
    label: "Australia/Broken_Hill",
    offset: 630,
    offsetMs: 37800000,
    formattedOffset: "UTC+10:30",
    localAbbr: "ACDT",
  },
  {
    key: "Australia/Canberra",
    label: "Australia/Canberra",
    offset: 660,
    offsetMs: 39600000,
    formattedOffset: "UTC+11:00",
    localAbbr: "AEDT",
  },
  {
    key: "Australia/Currie",
    label: "Australia/Currie",
    offset: 660,
    offsetMs: 39600000,
    formattedOffset: "UTC+11:00",
    localAbbr: "AEDT",
  },
  {
    key: "Australia/Darwin",
    label: "Australia/Darwin",
    offset: 570,
    offsetMs: 34200000,
    formattedOffset: "UTC+09:30",
    localAbbr: "ACST",
  },
  {
    key: "Australia/Eucla",
    label: "Australia/Eucla",
    offset: 525,
    offsetMs: 31500000,
    formattedOffset: "UTC+08:45",
    localAbbr: "+0845",
  },
  {
    key: "Australia/Hobart",
    label: "Australia/Hobart",
    offset: 660,
    offsetMs: 39600000,
    formattedOffset: "UTC+11:00",
    localAbbr: "AEDT",
  },
  {
    key: "Australia/LHI",
    label: "Australia/LHI",
    offset: 660,
    offsetMs: 39600000,
    formattedOffset: "UTC+11:00",
    localAbbr: "+11",
  },
  {
    key: "Australia/Lindeman",
    label: "Australia/Lindeman",
    offset: 600,
    offsetMs: 36000000,
    formattedOffset: "UTC+10:00",
    localAbbr: "AEST",
  },
  {
    key: "Australia/Lord_Howe",
    label: "Australia/Lord_Howe",
    offset: 660,
    offsetMs: 39600000,
    formattedOffset: "UTC+11:00",
    localAbbr: "+11",
  },
  {
    key: "Australia/Melbourne",
    label: "Australia/Melbourne",
    offset: 660,
    offsetMs: 39600000,
    formattedOffset: "UTC+11:00",
    localAbbr: "AEDT",
  },
  {
    key: "Australia/NSW",
    label: "Australia/NSW",
    offset: 660,
    offsetMs: 39600000,
    formattedOffset: "UTC+11:00",
    localAbbr: "AEDT",
  },
  {
    key: "Australia/North",
    label: "Australia/North",
    offset: 570,
    offsetMs: 34200000,
    formattedOffset: "UTC+09:30",
    localAbbr: "ACST",
  },
  {
    key: "Australia/Perth",
    label: "Australia/Perth",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "AWST",
  },
  {
    key: "Australia/Queensland",
    label: "Australia/Queensland",
    offset: 600,
    offsetMs: 36000000,
    formattedOffset: "UTC+10:00",
    localAbbr: "AEST",
  },
  {
    key: "Australia/South",
    label: "Australia/South",
    offset: 630,
    offsetMs: 37800000,
    formattedOffset: "UTC+10:30",
    localAbbr: "ACDT",
  },
  {
    key: "Australia/Sydney",
    label: "Australia/Sydney",
    offset: 660,
    offsetMs: 39600000,
    formattedOffset: "UTC+11:00",
    localAbbr: "AEDT",
  },
  {
    key: "Australia/Tasmania",
    label: "Australia/Tasmania",
    offset: 660,
    offsetMs: 39600000,
    formattedOffset: "UTC+11:00",
    localAbbr: "AEDT",
  },
  {
    key: "Australia/Victoria",
    label: "Australia/Victoria",
    offset: 660,
    offsetMs: 39600000,
    formattedOffset: "UTC+11:00",
    localAbbr: "AEDT",
  },
  {
    key: "Australia/West",
    label: "Australia/West",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "AWST",
  },
  {
    key: "Australia/Yancowinna",
    label: "Australia/Yancowinna",
    offset: 630,
    offsetMs: 37800000,
    formattedOffset: "UTC+10:30",
    localAbbr: "ACDT",
  },
  {
    key: "Brazil/Acre",
    label: "Brazil/Acre",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "-05",
  },
  {
    key: "Brazil/DeNoronha",
    label: "Brazil/DeNoronha",
    offset: -120,
    offsetMs: -7200000,
    formattedOffset: "UTC-02:00",
    localAbbr: "-02",
  },
  {
    key: "Brazil/East",
    label: "Brazil/East",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "Brazil/West",
    label: "Brazil/West",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "-04",
  },
  {
    key: "CET",
    label: "CET",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "CST6CDT",
    label: "CST6CDT",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "CDT",
  },
  {
    key: "Canada/Atlantic",
    label: "Canada/Atlantic",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "ADT",
  },
  {
    key: "Canada/Central",
    label: "Canada/Central",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "CDT",
  },
  {
    key: "Canada/Eastern",
    label: "Canada/Eastern",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "Canada/Mountain",
    label: "Canada/Mountain",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "MDT",
  },
  {
    key: "Canada/Newfoundland",
    label: "Canada/Newfoundland",
    offset: -150,
    offsetMs: -9000000,
    formattedOffset: "UTC-02:30",
    localAbbr: "NDT",
  },
  {
    key: "Canada/Pacific",
    label: "Canada/Pacific",
    offset: -420,
    offsetMs: -25200000,
    formattedOffset: "UTC-07:00",
    localAbbr: "PDT",
  },
  {
    key: "Canada/Saskatchewan",
    label: "Canada/Saskatchewan",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "CST",
  },
  {
    key: "Canada/Yukon",
    label: "Canada/Yukon",
    offset: -420,
    offsetMs: -25200000,
    formattedOffset: "UTC-07:00",
    localAbbr: "MST",
  },
  {
    key: "Chile/Continental",
    label: "Chile/Continental",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "Chile/EasterIsland",
    label: "Chile/EasterIsland",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "-05",
  },
  {
    key: "Cuba",
    label: "Cuba",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "CDT",
  },
  {
    key: "EET",
    label: "EET",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "EST",
    label: "EST",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "EST",
  },
  {
    key: "EST5EDT",
    label: "EST5EDT",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "Egypt",
    label: "Egypt",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Eire",
    label: "Eire",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Etc/GMT",
    label: "Etc/GMT",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Etc/GMT+0",
    label: "Etc/GMT+0",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Etc/GMT+1",
    label: "Etc/GMT+1",
    offset: -60,
    offsetMs: -3600000,
    formattedOffset: "UTC-01:00",
    localAbbr: "-01",
  },
  {
    key: "Etc/GMT+10",
    label: "Etc/GMT+10",
    offset: -600,
    offsetMs: -36000000,
    formattedOffset: "UTC-10:00",
    localAbbr: "-10",
  },
  {
    key: "Etc/GMT+11",
    label: "Etc/GMT+11",
    offset: -660,
    offsetMs: -39600000,
    formattedOffset: "UTC-11:00",
    localAbbr: "-11",
  },
  {
    key: "Etc/GMT+12",
    label: "Etc/GMT+12",
    offset: -720,
    offsetMs: -43200000,
    formattedOffset: "UTC-12:00",
    localAbbr: "-12",
  },
  {
    key: "Etc/GMT+2",
    label: "Etc/GMT+2",
    offset: -120,
    offsetMs: -7200000,
    formattedOffset: "UTC-02:00",
    localAbbr: "-02",
  },
  {
    key: "Etc/GMT+3",
    label: "Etc/GMT+3",
    offset: -180,
    offsetMs: -10800000,
    formattedOffset: "UTC-03:00",
    localAbbr: "-03",
  },
  {
    key: "Etc/GMT+4",
    label: "Etc/GMT+4",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "-04",
  },
  {
    key: "Etc/GMT+5",
    label: "Etc/GMT+5",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "-05",
  },
  {
    key: "Etc/GMT+6",
    label: "Etc/GMT+6",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "-06",
  },
  {
    key: "Etc/GMT+7",
    label: "Etc/GMT+7",
    offset: -420,
    offsetMs: -25200000,
    formattedOffset: "UTC-07:00",
    localAbbr: "-07",
  },
  {
    key: "Etc/GMT+8",
    label: "Etc/GMT+8",
    offset: -480,
    offsetMs: -28800000,
    formattedOffset: "UTC-08:00",
    localAbbr: "-08",
  },
  {
    key: "Etc/GMT+9",
    label: "Etc/GMT+9",
    offset: -540,
    offsetMs: -32400000,
    formattedOffset: "UTC-09:00",
    localAbbr: "-09",
  },
  {
    key: "Etc/GMT-0",
    label: "Etc/GMT-0",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Etc/GMT-1",
    label: "Etc/GMT-1",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "+01",
  },
  {
    key: "Etc/GMT-10",
    label: "Etc/GMT-10",
    offset: 600,
    offsetMs: 36000000,
    formattedOffset: "UTC+10:00",
    localAbbr: "+10",
  },
  {
    key: "Etc/GMT-11",
    label: "Etc/GMT-11",
    offset: 660,
    offsetMs: 39600000,
    formattedOffset: "UTC+11:00",
    localAbbr: "+11",
  },
  {
    key: "Etc/GMT-12",
    label: "Etc/GMT-12",
    offset: 720,
    offsetMs: 43200000,
    formattedOffset: "UTC+12:00",
    localAbbr: "+12",
  },
  {
    key: "Etc/GMT-13",
    label: "Etc/GMT-13",
    offset: 780,
    offsetMs: 46800000,
    formattedOffset: "UTC+13:00",
    localAbbr: "+13",
  },
  {
    key: "Etc/GMT-14",
    label: "Etc/GMT-14",
    offset: 840,
    offsetMs: 50400000,
    formattedOffset: "UTC+14:00",
    localAbbr: "+14",
  },
  {
    key: "Etc/GMT-2",
    label: "Etc/GMT-2",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "+02",
  },
  {
    key: "Etc/GMT-3",
    label: "Etc/GMT-3",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "+03",
  },
  {
    key: "Etc/GMT-4",
    label: "Etc/GMT-4",
    offset: 240,
    offsetMs: 14400000,
    formattedOffset: "UTC+04:00",
    localAbbr: "+04",
  },
  {
    key: "Etc/GMT-5",
    label: "Etc/GMT-5",
    offset: 300,
    offsetMs: 18000000,
    formattedOffset: "UTC+05:00",
    localAbbr: "+05",
  },
  {
    key: "Etc/GMT-6",
    label: "Etc/GMT-6",
    offset: 360,
    offsetMs: 21600000,
    formattedOffset: "UTC+06:00",
    localAbbr: "+06",
  },
  {
    key: "Etc/GMT-7",
    label: "Etc/GMT-7",
    offset: 420,
    offsetMs: 25200000,
    formattedOffset: "UTC+07:00",
    localAbbr: "+07",
  },
  {
    key: "Etc/GMT-8",
    label: "Etc/GMT-8",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "+08",
  },
  {
    key: "Etc/GMT-9",
    label: "Etc/GMT-9",
    offset: 540,
    offsetMs: 32400000,
    formattedOffset: "UTC+09:00",
    localAbbr: "+09",
  },
  {
    key: "Etc/GMT0",
    label: "Etc/GMT0",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Etc/Greenwich",
    label: "Etc/Greenwich",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Etc/UCT",
    label: "Etc/UCT",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "UTC",
  },
  {
    key: "Etc/UTC",
    label: "Etc/UTC",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "UTC",
  },
  {
    key: "Etc/Universal",
    label: "Etc/Universal",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "UTC",
  },
  {
    key: "Etc/Zulu",
    label: "Etc/Zulu",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "UTC",
  },
  {
    key: "Europe/Amsterdam",
    label: "Europe/Amsterdam",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Andorra",
    label: "Europe/Andorra",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Astrakhan",
    label: "Europe/Astrakhan",
    offset: 240,
    offsetMs: 14400000,
    formattedOffset: "UTC+04:00",
    localAbbr: "+04",
  },
  {
    key: "Europe/Athens",
    label: "Europe/Athens",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Europe/Belfast",
    label: "Europe/Belfast",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Europe/Belgrade",
    label: "Europe/Belgrade",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Berlin",
    label: "Europe/Berlin",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Bratislava",
    label: "Europe/Bratislava",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Brussels",
    label: "Europe/Brussels",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Bucharest",
    label: "Europe/Bucharest",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Europe/Budapest",
    label: "Europe/Budapest",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Busingen",
    label: "Europe/Busingen",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Chisinau",
    label: "Europe/Chisinau",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Europe/Copenhagen",
    label: "Europe/Copenhagen",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Dublin",
    label: "Europe/Dublin",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Europe/Gibraltar",
    label: "Europe/Gibraltar",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Guernsey",
    label: "Europe/Guernsey",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Europe/Helsinki",
    label: "Europe/Helsinki",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Europe/Isle_of_Man",
    label: "Europe/Isle_of_Man",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Europe/Istanbul",
    label: "Europe/Istanbul",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "+03",
  },
  {
    key: "Europe/Jersey",
    label: "Europe/Jersey",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Europe/Kaliningrad",
    label: "Europe/Kaliningrad",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Europe/Kiev",
    label: "Europe/Kiev",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Europe/Kirov",
    label: "Europe/Kirov",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "MSK",
  },
  {
    key: "Europe/Kyiv",
    label: "Europe/Kyiv",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Europe/Lisbon",
    label: "Europe/Lisbon",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "WET",
  },
  {
    key: "Europe/Ljubljana",
    label: "Europe/Ljubljana",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/London",
    label: "Europe/London",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Europe/Luxembourg",
    label: "Europe/Luxembourg",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Madrid",
    label: "Europe/Madrid",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Malta",
    label: "Europe/Malta",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Mariehamn",
    label: "Europe/Mariehamn",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Europe/Minsk",
    label: "Europe/Minsk",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "+03",
  },
  {
    key: "Europe/Monaco",
    label: "Europe/Monaco",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Moscow",
    label: "Europe/Moscow",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "MSK",
  },
  {
    key: "Europe/Nicosia",
    label: "Europe/Nicosia",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Europe/Oslo",
    label: "Europe/Oslo",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Paris",
    label: "Europe/Paris",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Podgorica",
    label: "Europe/Podgorica",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Prague",
    label: "Europe/Prague",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Riga",
    label: "Europe/Riga",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Europe/Rome",
    label: "Europe/Rome",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Samara",
    label: "Europe/Samara",
    offset: 240,
    offsetMs: 14400000,
    formattedOffset: "UTC+04:00",
    localAbbr: "+04",
  },
  {
    key: "Europe/San_Marino",
    label: "Europe/San_Marino",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Sarajevo",
    label: "Europe/Sarajevo",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Saratov",
    label: "Europe/Saratov",
    offset: 240,
    offsetMs: 14400000,
    formattedOffset: "UTC+04:00",
    localAbbr: "+04",
  },
  {
    key: "Europe/Simferopol",
    label: "Europe/Simferopol",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "MSK",
  },
  {
    key: "Europe/Skopje",
    label: "Europe/Skopje",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Sofia",
    label: "Europe/Sofia",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Europe/Stockholm",
    label: "Europe/Stockholm",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Tallinn",
    label: "Europe/Tallinn",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Europe/Tirane",
    label: "Europe/Tirane",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Tiraspol",
    label: "Europe/Tiraspol",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Europe/Ulyanovsk",
    label: "Europe/Ulyanovsk",
    offset: 240,
    offsetMs: 14400000,
    formattedOffset: "UTC+04:00",
    localAbbr: "+04",
  },
  {
    key: "Europe/Uzhgorod",
    label: "Europe/Uzhgorod",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Europe/Vaduz",
    label: "Europe/Vaduz",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Vatican",
    label: "Europe/Vatican",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Vienna",
    label: "Europe/Vienna",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Vilnius",
    label: "Europe/Vilnius",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Europe/Volgograd",
    label: "Europe/Volgograd",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "MSK",
  },
  {
    key: "Europe/Warsaw",
    label: "Europe/Warsaw",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Zagreb",
    label: "Europe/Zagreb",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Europe/Zaporozhye",
    label: "Europe/Zaporozhye",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "Europe/Zurich",
    label: "Europe/Zurich",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "GB",
    label: "GB",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "GB-Eire",
    label: "GB-Eire",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "GMT",
    label: "GMT",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "GMT+0",
    label: "GMT+0",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "GMT-0",
    label: "GMT-0",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "GMT0",
    label: "GMT0",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Greenwich",
    label: "Greenwich",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "HST",
    label: "HST",
    offset: -600,
    offsetMs: -36000000,
    formattedOffset: "UTC-10:00",
    localAbbr: "HST",
  },
  {
    key: "Hongkong",
    label: "Hongkong",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "HKT",
  },
  {
    key: "Iceland",
    label: "Iceland",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "GMT",
  },
  {
    key: "Indian/Antananarivo",
    label: "Indian/Antananarivo",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "EAT",
  },
  {
    key: "Indian/Chagos",
    label: "Indian/Chagos",
    offset: 360,
    offsetMs: 21600000,
    formattedOffset: "UTC+06:00",
    localAbbr: "+06",
  },
  {
    key: "Indian/Christmas",
    label: "Indian/Christmas",
    offset: 420,
    offsetMs: 25200000,
    formattedOffset: "UTC+07:00",
    localAbbr: "+07",
  },
  {
    key: "Indian/Cocos",
    label: "Indian/Cocos",
    offset: 390,
    offsetMs: 23400000,
    formattedOffset: "UTC+06:30",
    localAbbr: "+0630",
  },
  {
    key: "Indian/Comoro",
    label: "Indian/Comoro",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "EAT",
  },
  {
    key: "Indian/Kerguelen",
    label: "Indian/Kerguelen",
    offset: 300,
    offsetMs: 18000000,
    formattedOffset: "UTC+05:00",
    localAbbr: "+05",
  },
  {
    key: "Indian/Mahe",
    label: "Indian/Mahe",
    offset: 240,
    offsetMs: 14400000,
    formattedOffset: "UTC+04:00",
    localAbbr: "+04",
  },
  {
    key: "Indian/Maldives",
    label: "Indian/Maldives",
    offset: 300,
    offsetMs: 18000000,
    formattedOffset: "UTC+05:00",
    localAbbr: "+05",
  },
  {
    key: "Indian/Mauritius",
    label: "Indian/Mauritius",
    offset: 240,
    offsetMs: 14400000,
    formattedOffset: "UTC+04:00",
    localAbbr: "+04",
  },
  {
    key: "Indian/Mayotte",
    label: "Indian/Mayotte",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "EAT",
  },
  {
    key: "Indian/Reunion",
    label: "Indian/Reunion",
    offset: 240,
    offsetMs: 14400000,
    formattedOffset: "UTC+04:00",
    localAbbr: "+04",
  },
  {
    key: "Iran",
    label: "Iran",
    offset: 210,
    offsetMs: 12600000,
    formattedOffset: "UTC+03:30",
    localAbbr: "+0330",
  },
  {
    key: "Israel",
    label: "Israel",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "IST",
  },
  {
    key: "Jamaica",
    label: "Jamaica",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "EST",
  },
  {
    key: "Japan",
    label: "Japan",
    offset: 540,
    offsetMs: 32400000,
    formattedOffset: "UTC+09:00",
    localAbbr: "JST",
  },
  {
    key: "Kwajalein",
    label: "Kwajalein",
    offset: 720,
    offsetMs: 43200000,
    formattedOffset: "UTC+12:00",
    localAbbr: "+12",
  },
  {
    key: "Libya",
    label: "Libya",
    offset: 120,
    offsetMs: 7200000,
    formattedOffset: "UTC+02:00",
    localAbbr: "EET",
  },
  {
    key: "MET",
    label: "MET",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "MST",
    label: "MST",
    offset: -420,
    offsetMs: -25200000,
    formattedOffset: "UTC-07:00",
    localAbbr: "MST",
  },
  {
    key: "MST7MDT",
    label: "MST7MDT",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "MDT",
  },
  {
    key: "Mexico/BajaNorte",
    label: "Mexico/BajaNorte",
    offset: -420,
    offsetMs: -25200000,
    formattedOffset: "UTC-07:00",
    localAbbr: "PDT",
  },
  {
    key: "Mexico/BajaSur",
    label: "Mexico/BajaSur",
    offset: -420,
    offsetMs: -25200000,
    formattedOffset: "UTC-07:00",
    localAbbr: "MST",
  },
  {
    key: "Mexico/General",
    label: "Mexico/General",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "CST",
  },
  {
    key: "NZ",
    label: "NZ",
    offset: 780,
    offsetMs: 46800000,
    formattedOffset: "UTC+13:00",
    localAbbr: "NZDT",
  },
  {
    key: "NZ-CHAT",
    label: "NZ-CHAT",
    offset: 825,
    offsetMs: 49500000,
    formattedOffset: "UTC+13:45",
    localAbbr: "+1345",
  },
  {
    key: "Navajo",
    label: "Navajo",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "MDT",
  },
  {
    key: "PRC",
    label: "PRC",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "CST",
  },
  {
    key: "PST8PDT",
    label: "PST8PDT",
    offset: -420,
    offsetMs: -25200000,
    formattedOffset: "UTC-07:00",
    localAbbr: "PDT",
  },
  {
    key: "Pacific/Apia",
    label: "Pacific/Apia",
    offset: 780,
    offsetMs: 46800000,
    formattedOffset: "UTC+13:00",
    localAbbr: "+13",
  },
  {
    key: "Pacific/Auckland",
    label: "Pacific/Auckland",
    offset: 780,
    offsetMs: 46800000,
    formattedOffset: "UTC+13:00",
    localAbbr: "NZDT",
  },
  {
    key: "Pacific/Bougainville",
    label: "Pacific/Bougainville",
    offset: 660,
    offsetMs: 39600000,
    formattedOffset: "UTC+11:00",
    localAbbr: "+11",
  },
  {
    key: "Pacific/Chatham",
    label: "Pacific/Chatham",
    offset: 825,
    offsetMs: 49500000,
    formattedOffset: "UTC+13:45",
    localAbbr: "+1345",
  },
  {
    key: "Pacific/Chuuk",
    label: "Pacific/Chuuk",
    offset: 600,
    offsetMs: 36000000,
    formattedOffset: "UTC+10:00",
    localAbbr: "+10",
  },
  {
    key: "Pacific/Easter",
    label: "Pacific/Easter",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "-05",
  },
  {
    key: "Pacific/Efate",
    label: "Pacific/Efate",
    offset: 660,
    offsetMs: 39600000,
    formattedOffset: "UTC+11:00",
    localAbbr: "+11",
  },
  {
    key: "Pacific/Enderbury",
    label: "Pacific/Enderbury",
    offset: 780,
    offsetMs: 46800000,
    formattedOffset: "UTC+13:00",
    localAbbr: "+13",
  },
  {
    key: "Pacific/Fakaofo",
    label: "Pacific/Fakaofo",
    offset: 780,
    offsetMs: 46800000,
    formattedOffset: "UTC+13:00",
    localAbbr: "+13",
  },
  {
    key: "Pacific/Fiji",
    label: "Pacific/Fiji",
    offset: 720,
    offsetMs: 43200000,
    formattedOffset: "UTC+12:00",
    localAbbr: "+12",
  },
  {
    key: "Pacific/Funafuti",
    label: "Pacific/Funafuti",
    offset: 720,
    offsetMs: 43200000,
    formattedOffset: "UTC+12:00",
    localAbbr: "+12",
  },
  {
    key: "Pacific/Galapagos",
    label: "Pacific/Galapagos",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "-06",
  },
  {
    key: "Pacific/Gambier",
    label: "Pacific/Gambier",
    offset: -540,
    offsetMs: -32400000,
    formattedOffset: "UTC-09:00",
    localAbbr: "-09",
  },
  {
    key: "Pacific/Guadalcanal",
    label: "Pacific/Guadalcanal",
    offset: 660,
    offsetMs: 39600000,
    formattedOffset: "UTC+11:00",
    localAbbr: "+11",
  },
  {
    key: "Pacific/Guam",
    label: "Pacific/Guam",
    offset: 600,
    offsetMs: 36000000,
    formattedOffset: "UTC+10:00",
    localAbbr: "ChST",
  },
  {
    key: "Pacific/Honolulu",
    label: "Pacific/Honolulu",
    offset: -600,
    offsetMs: -36000000,
    formattedOffset: "UTC-10:00",
    localAbbr: "HST",
  },
  {
    key: "Pacific/Johnston",
    label: "Pacific/Johnston",
    offset: -600,
    offsetMs: -36000000,
    formattedOffset: "UTC-10:00",
    localAbbr: "HST",
  },
  {
    key: "Pacific/Kanton",
    label: "Pacific/Kanton",
    offset: 780,
    offsetMs: 46800000,
    formattedOffset: "UTC+13:00",
    localAbbr: "+13",
  },
  {
    key: "Pacific/Kiritimati",
    label: "Pacific/Kiritimati",
    offset: 840,
    offsetMs: 50400000,
    formattedOffset: "UTC+14:00",
    localAbbr: "+14",
  },
  {
    key: "Pacific/Kosrae",
    label: "Pacific/Kosrae",
    offset: 660,
    offsetMs: 39600000,
    formattedOffset: "UTC+11:00",
    localAbbr: "+11",
  },
  {
    key: "Pacific/Kwajalein",
    label: "Pacific/Kwajalein",
    offset: 720,
    offsetMs: 43200000,
    formattedOffset: "UTC+12:00",
    localAbbr: "+12",
  },
  {
    key: "Pacific/Majuro",
    label: "Pacific/Majuro",
    offset: 720,
    offsetMs: 43200000,
    formattedOffset: "UTC+12:00",
    localAbbr: "+12",
  },
  {
    key: "Pacific/Marquesas",
    label: "Pacific/Marquesas",
    offset: -570,
    offsetMs: -34200000,
    formattedOffset: "UTC-09:30",
    localAbbr: "-0930",
  },
  {
    key: "Pacific/Midway",
    label: "Pacific/Midway",
    offset: -660,
    offsetMs: -39600000,
    formattedOffset: "UTC-11:00",
    localAbbr: "SST",
  },
  {
    key: "Pacific/Nauru",
    label: "Pacific/Nauru",
    offset: 720,
    offsetMs: 43200000,
    formattedOffset: "UTC+12:00",
    localAbbr: "+12",
  },
  {
    key: "Pacific/Niue",
    label: "Pacific/Niue",
    offset: -660,
    offsetMs: -39600000,
    formattedOffset: "UTC-11:00",
    localAbbr: "-11",
  },
  {
    key: "Pacific/Norfolk",
    label: "Pacific/Norfolk",
    offset: 720,
    offsetMs: 43200000,
    formattedOffset: "UTC+12:00",
    localAbbr: "+12",
  },
  {
    key: "Pacific/Noumea",
    label: "Pacific/Noumea",
    offset: 660,
    offsetMs: 39600000,
    formattedOffset: "UTC+11:00",
    localAbbr: "+11",
  },
  {
    key: "Pacific/Pago_Pago",
    label: "Pacific/Pago_Pago",
    offset: -660,
    offsetMs: -39600000,
    formattedOffset: "UTC-11:00",
    localAbbr: "SST",
  },
  {
    key: "Pacific/Palau",
    label: "Pacific/Palau",
    offset: 540,
    offsetMs: 32400000,
    formattedOffset: "UTC+09:00",
    localAbbr: "+09",
  },
  {
    key: "Pacific/Pitcairn",
    label: "Pacific/Pitcairn",
    offset: -480,
    offsetMs: -28800000,
    formattedOffset: "UTC-08:00",
    localAbbr: "-08",
  },
  {
    key: "Pacific/Pohnpei",
    label: "Pacific/Pohnpei",
    offset: 660,
    offsetMs: 39600000,
    formattedOffset: "UTC+11:00",
    localAbbr: "+11",
  },
  {
    key: "Pacific/Ponape",
    label: "Pacific/Ponape",
    offset: 660,
    offsetMs: 39600000,
    formattedOffset: "UTC+11:00",
    localAbbr: "+11",
  },
  {
    key: "Pacific/Port_Moresby",
    label: "Pacific/Port_Moresby",
    offset: 600,
    offsetMs: 36000000,
    formattedOffset: "UTC+10:00",
    localAbbr: "+10",
  },
  {
    key: "Pacific/Rarotonga",
    label: "Pacific/Rarotonga",
    offset: -600,
    offsetMs: -36000000,
    formattedOffset: "UTC-10:00",
    localAbbr: "-10",
  },
  {
    key: "Pacific/Saipan",
    label: "Pacific/Saipan",
    offset: 600,
    offsetMs: 36000000,
    formattedOffset: "UTC+10:00",
    localAbbr: "ChST",
  },
  {
    key: "Pacific/Samoa",
    label: "Pacific/Samoa",
    offset: -660,
    offsetMs: -39600000,
    formattedOffset: "UTC-11:00",
    localAbbr: "SST",
  },
  {
    key: "Pacific/Tahiti",
    label: "Pacific/Tahiti",
    offset: -600,
    offsetMs: -36000000,
    formattedOffset: "UTC-10:00",
    localAbbr: "-10",
  },
  {
    key: "Pacific/Tarawa",
    label: "Pacific/Tarawa",
    offset: 720,
    offsetMs: 43200000,
    formattedOffset: "UTC+12:00",
    localAbbr: "+12",
  },
  {
    key: "Pacific/Tongatapu",
    label: "Pacific/Tongatapu",
    offset: 780,
    offsetMs: 46800000,
    formattedOffset: "UTC+13:00",
    localAbbr: "+13",
  },
  {
    key: "Pacific/Truk",
    label: "Pacific/Truk",
    offset: 600,
    offsetMs: 36000000,
    formattedOffset: "UTC+10:00",
    localAbbr: "+10",
  },
  {
    key: "Pacific/Wake",
    label: "Pacific/Wake",
    offset: 720,
    offsetMs: 43200000,
    formattedOffset: "UTC+12:00",
    localAbbr: "+12",
  },
  {
    key: "Pacific/Wallis",
    label: "Pacific/Wallis",
    offset: 720,
    offsetMs: 43200000,
    formattedOffset: "UTC+12:00",
    localAbbr: "+12",
  },
  {
    key: "Pacific/Yap",
    label: "Pacific/Yap",
    offset: 600,
    offsetMs: 36000000,
    formattedOffset: "UTC+10:00",
    localAbbr: "+10",
  },
  {
    key: "Poland",
    label: "Poland",
    offset: 60,
    offsetMs: 3600000,
    formattedOffset: "UTC+01:00",
    localAbbr: "CET",
  },
  {
    key: "Portugal",
    label: "Portugal",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "WET",
  },
  {
    key: "ROC",
    label: "ROC",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "CST",
  },
  {
    key: "ROK",
    label: "ROK",
    offset: 540,
    offsetMs: 32400000,
    formattedOffset: "UTC+09:00",
    localAbbr: "KST",
  },
  {
    key: "Singapore",
    label: "Singapore",
    offset: 480,
    offsetMs: 28800000,
    formattedOffset: "UTC+08:00",
    localAbbr: "+08",
  },
  {
    key: "Turkey",
    label: "Turkey",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "+03",
  },
  {
    key: "UCT",
    label: "UCT",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "UTC",
  },
  {
    key: "US/Alaska",
    label: "US/Alaska",
    offset: -480,
    offsetMs: -28800000,
    formattedOffset: "UTC-08:00",
    localAbbr: "AKDT",
  },
  {
    key: "US/Aleutian",
    label: "US/Aleutian",
    offset: -540,
    offsetMs: -32400000,
    formattedOffset: "UTC-09:00",
    localAbbr: "HDT",
  },
  {
    key: "US/Arizona",
    label: "US/Arizona",
    offset: -420,
    offsetMs: -25200000,
    formattedOffset: "UTC-07:00",
    localAbbr: "MST",
  },
  {
    key: "US/Central",
    label: "US/Central",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "CDT",
  },
  {
    key: "US/East-Indiana",
    label: "US/East-Indiana",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "US/Eastern",
    label: "US/Eastern",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "US/Hawaii",
    label: "US/Hawaii",
    offset: -600,
    offsetMs: -36000000,
    formattedOffset: "UTC-10:00",
    localAbbr: "HST",
  },
  {
    key: "US/Indiana-Starke",
    label: "US/Indiana-Starke",
    offset: -300,
    offsetMs: -18000000,
    formattedOffset: "UTC-05:00",
    localAbbr: "CDT",
  },
  {
    key: "US/Michigan",
    label: "US/Michigan",
    offset: -240,
    offsetMs: -14400000,
    formattedOffset: "UTC-04:00",
    localAbbr: "EDT",
  },
  {
    key: "US/Mountain",
    label: "US/Mountain",
    offset: -360,
    offsetMs: -21600000,
    formattedOffset: "UTC-06:00",
    localAbbr: "MDT",
  },
  {
    key: "US/Pacific",
    label: "US/Pacific",
    offset: -420,
    offsetMs: -25200000,
    formattedOffset: "UTC-07:00",
    localAbbr: "PDT",
  },
  {
    key: "US/Samoa",
    label: "US/Samoa",
    offset: -660,
    offsetMs: -39600000,
    formattedOffset: "UTC-11:00",
    localAbbr: "SST",
  },
  {
    key: "UTC",
    label: "UTC",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "UTC",
  },
  {
    key: "Universal",
    label: "Universal",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "UTC",
  },
  {
    key: "W-SU",
    label: "W-SU",
    offset: 180,
    offsetMs: 10800000,
    formattedOffset: "UTC+03:00",
    localAbbr: "MSK",
  },
  {
    key: "WET",
    label: "WET",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "WET",
  },
  {
    key: "Zulu",
    label: "Zulu",
    offset: 0,
    offsetMs: 0,
    formattedOffset: "UTC+00:00",
    localAbbr: "UTC",
  },
];
